[project]
name = "agents"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "nest-asyncio>=1.6.0",
    "openai-agents>=0.2.9",
    "python-dotenv>=1.1.1",
]
